checking summation of outputs

diff --git a/.github/workflows/pr-type-category.yml b/.github/workflows/pr-type-category.yml
--- a/.github/workflows/pr-type-category.yml
+++ b/.github/workflows/pr-type-category.yml
@@ -9,29 +9,76 @@ jobs:
     runs-on: ubuntu-latest
     name: Check PR Category and Type
     steps:
-      - name: "Failed to find proper PR Type label. Please add one of the following: 'New Feature', 'Enhancement', or 'Bug-Fix'"
-        run: exit 1
-        if: |
-          !contains(github.event.pull_request.labels.*.name, 'New Feature') &&
-          !contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
-          !contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
-      - name: "Found more than one PR Type label. Please add only one of the following: 'New Feature', 'Enhancement', or 'Bug-Fix'"
-        run: exit 1
-        if: |
-          (
-            contains(github.event.pull_request.labels.*.name, 'New Feature') &&
-            contains(github.event.pull_request.labels.*.name, 'Enhancement')
-          ) || (
-            contains(github.event.pull_request.labels.*.name, 'New Feature') &&
-            contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
-          ) || (
-            contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
-            contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
-          )
-      - name: "PR Category is missing from PR title. Please add it like '<category>: <pr title>'"
-        run: |
-          if [[ ! "${{ github.event.pull_request.title }}" =~ ^.{2,}\:.{2,} ]]; then
-            exit 1
-          fi
-      - name: "Found at least one PR Type label and Category in the title. Good job!"
-        run: exit 0
+      - if: contains(github.event.pull_request.labels.*.name, 'New Feature')
+        id: new-feature
+        run: echo '::set-output name=COUNT::1'
+      - if: contains(github.event.pull_request.labels.*.name, 'Enhancement')
+        id: enhancement
+        run: echo '::set-output name=COUNT::1'
+      - if: contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
+        id: bug-fix
+        run: echo '::set-output name=COUNT::1'
+      - if: contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled')
+        id: not-yet-enabled
+        run: echo '::set-output name=COUNT::1'
+      - if: contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
+        id: skip-release-notes
+        run: echo '::set-output name=COUNT::1'
+
+      - run: |
+          echo $(( \
+            steps.id.outputs.COUNT + \
+            steps.id.outputs.COUNT + \
+            steps.id.outputs.COUNT + \
+            steps.id.outputs.COUNT + \
+            steps.id.outputs.COUNT ))
+
+      # - name: "Failed to find proper PR Type label. Please add one of the following: 'New Feature', 'Enhancement', or 'Bug-Fix'"
+      #   run: exit 1
+      #   if: |
+      #     !contains(github.event.pull_request.labels.*.name, 'New Feature') &&
+      #     !contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
+      #     !contains(github.event.pull_request.labels.*.name, 'Bug-Fix') &&
+      #     !contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled') &&
+      #     !contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
+      # - name: "Found more than one PR Type label. Please add only one of the following: 'New Feature', 'Enhancement', 'Bug-Fix', 'Not-Yet-Enabled', or 'Skip-Release-Notes'"
+      #   run: exit 1
+      #   if: |
+      #     (
+      #       contains(github.event.pull_request.labels.*.name, 'New Feature') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Enhancement')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'New Feature') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'New Feature') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'New Feature') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'Bug-Fix') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'Bug-Fix') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
+      #     ) || (
+      #       contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled') &&
+      #       contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
+      #     )
+      # - name: "PR Category is missing from PR title. Please add it like '<category>: <pr title>'"
+      #   run: |
+      #     if [[ ! "${{ github.event.pull_request.title }}" =~ ^.{2,}\:.{2,} ]]; then
+      #       exit 1
+      #     fi
+      # - name: "Found at least one PR Type label and Category in the title. Good job!"
+      #   run: exit 0
